rules:
  - id: External-Control-of-System-or-Configuration-Setting
    metadata:
      confidence: MEDIUM
      category: security
      cwe:
        - "CWE-15: External Control of System or Configuration Setting"
      vulnerability_class:
        - Memory Issues
      references:
        - https://cwe.mitre.org/data/definitions/15.html
    languages:
      - c
      - c++
    severity: WARNING
    message: >-
      One or more system settings or configuration elements can be externally controlled by a user. This vulnerability arises when the program sets system or configuration properties using inputs from external sources without proper validation. The lack of validation can lead to unauthorized control over system settings or configurations, potentially resulting in security breaches, data corruption, or loss of system integrity. Programs should sanitize and validate inputs before using them to modify system or configuration settings to mitigate this risk.
    patterns:
      - pattern-either:
        - patterns:
          - pattern: $FUNC(..., <... $VAR ...>, ...);
          - pattern: $FUNC(<... $VAR ...>, ...);
          - pattern-not: $FUNC($VAR, $LITERAL);
          - pattern-not: $FUNC(...,$VAR, $LITERAL);
        
      - metavariable-regex:
          metavariable: $FUNC
          regex: (recv$|strcpy$)
